[build]
  command = "npm run build"
  publish = ".output/public"

[functions]
  directory = ".netlify/functions"
[build.environment]
  NPM_FLAGS = "--no-frozen-lockfile"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"